obligations:
  # 2 way match
  - name: 2-way-(Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: >
      MATCHONCE(ItemCategory == '2-way match')
    trigger: > 
      MATCH(Event == 'Clear Invoice') && 
      ~MATCH(Event == 'Change Approval for Purchase Order')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  # Consignment
  - name: consignment-(Create Purchase Order Item -> Record Goods Receipt, Single=False)
    type: maintenance
    filter: MATCHONCE(ItemType == 'Consignment')
    trigger: MATCH(Event == 'Record Goods Receipt')
    requirement: >
      INCDEC(
        Event == 'Create Purchase Order Item',
        Event == 'Record Goods Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: consignment-(Create Purchase Order Item -> Record Goods Receipt, Single=True)
    type: achievement
    filter: MATCHONCE(ItemType == 'Consignment')
    trigger: MATCH(Event == 'Record Goods Receipt')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item') &&
      BEFORE(
        MATCH(Event == 'Create Purchase Order Item'),
        MATCH(Event == 'Record Goods Receipt')
      )
    deadline: "false"
    domain: [Key]

  # 3-way after ec 
  - name: 3-way-after-ec-(Record Goods Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Record Goods Receipt -> Clear Invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Goods Receipt') &&
      BEFORE(
        MATCH(Event == 'Record Goods Receipt'),
        MATCH(Event == 'Clear Invoice')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Record Goods Receipt -> Record Invoice Receipt, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Record Invoice Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Record Invoice Receipt -> Clear Invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Invoice Receipt') &&
      BEFORE(
        MATCH(Event == 'Record Invoice Receipt'),
        MATCH(Event == 'Clear Invoice')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Vendor creates invoice -> Record Invoice Receipt, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      MATCH(Event == 'Vendor creates invoice') &&
      BEFORE(
        MATCH(Event == 'Vendor creates invoice'),
        MATCH(Event == 'Record Invoice Receipt')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-ec-(Create Purchase Order Item -> Vendor creates invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Vendor creates invoice')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item') &&
      BEFORE(
        MATCH(Event == 'Create Purchase Order Item'),
        MATCH(Event == 'Vendor creates invoice')
      )
    deadline: "false"
    domain: [Key]

  # 3-way after w/o ec
  - name: 3-way-after-wo-ec-(Vendor creates invoice -> Record Invoice Receipt, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      MATCH(Event == 'Vendor creates invoice') &&
      BEFORE(
        MATCH(Event == 'Vendor creates invoice'),
        MATCH(Event == 'Record Invoice Receipt')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-wo-ec-(Record Goods Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-wo-ec-(Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-wo-ec-(Record Goods Receipt -> Record Invoice Receipt, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Record Invoice Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-wo-ec-(Create Purchase Order Item -> Change Approval for Purchase Order, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Change Approval for Purchase Order')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item') &&
      BEFORE(
        MATCH(Event == 'Create Purchase Order Item'),
        MATCH(Event == 'Change Approval for Purchase Order')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-after-wo-ec-(Create Purchase Order Item -> Vendor creates invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice after GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Vendor creates invoice')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item') &&
      BEFORE(
        MATCH(Event == 'Create Purchase Order Item'),
        MATCH(Event == 'Vendor creates invoice')
      )
    deadline: "false"
    domain: [Key]

  # 3-way before ec
  - name: 3-way-before-ec-(Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-ec-(Record Goods Receipt -> Record Invoice Receipt, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Record Invoice Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-ec-(Record Goods Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-ec-(Record Goods Receipt -> Clear Invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Goods Receipt') &&
      BEFORE(
        MATCH(Event == 'Record Goods Receipt'),
        MATCH(Event == 'Clear Invoice')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-ec-(Vendor creates invoice -> Record Invoice Receipt, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      MATCH(Event == 'Vendor creates invoice') &&
      BEFORE(
        MATCH(Event == 'Vendor creates invoice'),
        MATCH(Event == 'Record Invoice Receipt')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-ec-(Set Payment Block -> Remove Payment Block, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType == 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Remove Payment Block')
    requirement: >
      MATCH(Event == 'Set Payment Block') &&
      BEFORE(
        MATCH(Event == 'Set Payment Block'),
        MATCH(Event == 'Remove Payment Block')
      )
    deadline: "false"
    domain: [Key]

  # 3-way before w/o ec
  - name: 3-way-before-wo-ec-(Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-wo-ec-(Record Invoice Receipt -> Clear Invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Invoice Receipt') &&
      BEFORE(
        MATCH(Event == 'Record Invoice Receipt'),
        MATCH(Event == 'Clear Invoice')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-wo-ec-(Record Goods Receipt -> Clear Invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-wo-ec-(Record Goods Receipt -> Clear Invoice, Single=True)
    type: achievement
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Goods Receipt') &&
      BEFORE(
        MATCH(Event == 'Record Goods Receipt'),
        MATCH(Event == 'Clear Invoice')
      )
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-wo-ec-(Record Invoice Receipt -> Vendor creates invoice, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Vendor creates invoice')
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Vendor creates invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: 3-way-before-wo-ec-(Set Payment Block -> Remove Payment Block, Single=False)
    type: maintenance
    filter: > 
      MATCHONCE(
        ItemCategory == '3-way match, invoice before GR' && 
        DocumentType != 'EC Purchase order'
      )
    trigger: MATCH(Event == 'Remove Payment Block')
    requirement: >
      INCDEC(
        Event == 'Set Payment Block',
        Event == 'Remove Payment Block'
      ) >= 0
    deadline: "false"
    domain: [Key]