filter: >
  ItemCategory == '2-way match'

obligations:
  - name: (Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    trigger: "true"
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: MATCH(Event == 'Change Approval for Purchase Order')
    domain: [Key]