obligations:
  - name: Invoice Receipt
    type: maintenance
    filter: MATCHONCE(ItemType != 'Service' && ItemCategory == '3-way match, invoice after GR')
    trigger: >
      LAST(Amount, Event == 'Record Invoice Receipt')<=2147483647 &&
      LAST(Amount, Event == 'Vendor creates invoice')<=2147483647
    requirement: >
      LAST(Amount, Event == 'Record Invoice Receipt') == LAST(Amount, Event == 'Vendor creates invoice')
    deadline: "true"
    domain: [PurchasingDocument, Item]