obligations:
  - name: Max PO Lifecycle
    type: achievement
    filter: MATCHONCE(ItemType != 'Service')
    trigger: >
      MATCH(Event == 'Clear Invoice') &&
      MATCH(Event == 'Vendor creates invoice')
    requirement: >
      END() && 
      DAYS_BETWEEN(
        MATCH(Event == 'Vendor creates invoice'), 
        MATCH(Event == 'Clear Invoice')
      ) < 21
    deadline: "false"
    domain: [PurchasingDocument, Item]