obligations:
  - name: Invoice Receipt
    type: achievement
    trigger: >
      MATCH(ItemCategory == '3-way match, invoice after GR') &&
      MATCH(Event == 'Record Invoice Receipt') &&
      MATCH(Event == 'Vendor creates invoice') &&
      MATCH(ItemType != 'Service')
    requirement: >
      END() && 
      LAST(Amount, Event == 'Record Invoice Receipt') == LAST(Amount, Event == 'Vendor creates invoice')
    deadline: "false"
    domain: [PurchasingDocument, Item]

  - name: Max Open Order Per User
    type: maintenance
    trigger: >
      MATCH(Event == 'Vendor creates invoice')
    requirement: >
      COUNTIF(Event == 'Vendor creates invoice') -
      COUNTIF(Event == 'Clear Invoice') -
      COUNTIF(Event == 'Cancel Subsequent Invoice') < 500
    deadline: "false"
    domain: [Vendor]
    
  - name: Max PO Lifecycle
    type: achievement
    trigger: >
      MATCH(Event == 'Clear Invoice') &&
      MATCH(Event == 'Vendor creates invoice') &&
      MATCH(ItemType != 'Service')
    requirement: >
      END() && 
      DAYS_BETWEEN(
        MATCH(Event == 'Vendor creates invoice'), 
        MATCH(Event == 'Clear Invoice')
      ) < 21
    deadline: "false"
    domain: [PurchasingDocument, Item]