obligations:
  - name: Max Open Order Per User
    type: maintenance
    trigger: "true"
    requirement: >
      COUNTIF(Event == 'Vendor creates invoice') -
      COUNTIF(Event == 'Clear Invoice') -
      COUNTIF(Event == 'Cancel Subsequent Invoice') < 500
    deadline: "false"
    domain: [Vendor]