obligations:
  - name: Max PO Lifecycle
    type: maintenance
    filter: ItemType != 'Service'
    trigger: >
      notNull(DAYS_BETWEEN(
        Event == 'Vendor creates invoice', 
       Event == 'Clear Invoice'
      ))
    requirement: >
      DAYS_BETWEEN(
       Event == 'Vendor creates invoice', 
       Event == 'Clear Invoice'
      ) < 21
    deadline: "true"
    domain: [PurchasingDocument, Item]