obligations:
  - name: Invoice Receipt
    type: maintenance
    filter: ItemType != 'Service' && ItemCategory == '3-way match, invoice after GR'
    trigger: >
      notNull(LAST(Amount, Event == 'Record Invoice Receipt')) &&
      notNull(LAST(Amount, Event == 'Vendor creates invoice'))
    requirement: >
      LAST(Amount, Event == 'Record Invoice Receipt') == LAST(Amount, Event == 'Vendor creates invoice')
    deadline: "true"
    domain: [PurchasingDocument, Item]