obligations:
  - name: Max PO Lifecycle
    type: maintenance
    filter: MATCHONCE(ItemType != 'Service')
    trigger: >
      DAYS_BETWEEN(
        Event == 'Vendor creates invoice', 
       Event == 'Clear Invoice'
      ) >= 0
    requirement: >
      DAYS_BETWEEN(
       Event == 'Vendor creates invoice', 
       Event == 'Clear Invoice'
      ) < 21
    deadline: "true"
    domain: [PurchasingDocument, Item]