filter: ItemType == 'Consignment'

obligations:
  - name: (Create Purchase Order Item -> Record Goods Receipt, Single=False)
    type: maintenance
    trigger: "true"
    requirement: >
      INCDEC(
        Event == 'Create Purchase Order Item',
        Event == 'Record Goods Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: (Create Purchase Order Item -> Record Goods Receipt, Single=True)
    type: maintenance
    trigger: MATCH(Event == 'Record Goods Receipt')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item')
    deadline: "true"
    domain: [Key]