filter: > 
  ItemCategory == '3-way match, invoice after GR' && 
    DocumentType == 'EC Purchase order'

obligations:
  - name: (Record Goods Receipt -> Clear Invoice, Single=False)
    type: maintenance
    trigger: "true"
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: (Record Invoice Receipt -> Clear Invoice, Single=False)
    type: maintenance
    trigger: "true"
    requirement: >
      INCDEC(
        Event == 'Record Invoice Receipt',
        Event == 'Clear Invoice'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: (Record Goods Receipt -> Clear Invoice, Single=True)
    type: maintenance
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Goods Receipt')
    deadline: "true"
    domain: [Key]

  - name: (Record Goods Receipt -> Record Invoice Receipt, Single=False)
    type: maintenance
    trigger: "true"
    requirement: >
      INCDEC(
        Event == 'Record Goods Receipt',
        Event == 'Record Invoice Receipt'
      ) >= 0
    deadline: "false"
    domain: [Key]

  - name: (Record Invoice Receipt -> Clear Invoice, Single=True)
    type: maintenance
    trigger: MATCH(Event == 'Clear Invoice')
    requirement: >
      MATCH(Event == 'Record Invoice Receipt')
    deadline: "true"
    domain: [Key]

  - name: (Vendor creates invoice -> Record Invoice Receipt, Single=True)
    type: maintenance
    trigger: MATCH(Event == 'Record Invoice Receipt')
    requirement: >
      MATCH(Event == 'Vendor creates invoice')
    deadline: "true"
    domain: [Key]

  - name: (Create Purchase Order Item -> Vendor creates invoice, Single=True)
    type: maintenance
    trigger: MATCH(Event == 'Vendor creates invoice')
    requirement: >
      MATCH(Event == 'Create Purchase Order Item')
    deadline: "true"
    domain: [Key]